### ISSUE TITLE
Confused how to consume these plugins.

### ISSUE THREAD

**Issue by Roger-Heathcote** [boourns/wam-community#12]
Hi WAM Community!

I just watched Michel Buffa's ADC talk on WAM2, and I'd love to try using these plugins in my web audio app, but I'm struggling to figure out how to use them. The talk makes a point of saying WAM2 plugins are just a URI, but I haven't found a list of public URIs for these plugins and your docs says my `application is responsible for serving the WAMs and their assets over HTTP to the user's browser.` From what I can tell the standard approach is to use this package's NPM module to get the files, then somehow serve them alongside your app, maybe by linking to them, or copying them from the node_modules folder?

I am not currently using node or a build system, and would ideally keep it that way. So I'm wondering if I can I create the URIs I need by simply copying the plugin folders I want, from `/plugins/wimmics`, to some public web hosting? Might that work?

And consuming those plugins in my app will require a host right? I found this on npm: https://www.npmjs.com/package/wam-host which looks like it might fit the bill. I'm hoping I can consume it dynamically via unpkg. May that work? Or am I barking up the wrong tree here?

If I can figure the basics out, I'd like to try and contribute some newbie docs / tutorials, on how to use WAM2 plugins. It's super cool tech, but I'm drawing a blank on accessible onboarding docs / tutorials rn. [Michel's presentation](https://inria.hal.science/hal-03871660/document) gives a link to `several` `step by step tutorials` [here](https://wam-examples.vidalmazuy.fr/) but the link is dead :/

Thanks!

**Comment by boourns** [comment]
@Roger-Heathcote sorry for the delay in responding, Just seeing this post now.

The most recent release of wam-community is hosted at https://www.webaudiomodules.com/community.  For example, you can download the plugin index here https://www.webaudiomodules.com/community/plugins.json which describes each plugin, and provides the link to load each plugin.
